// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import '_homepage_test.dart' as _homepage_test;
import '_main_test.dart' as _main_test;
import '_navigation_test.dart' as _navigation_test;
import '_vibrate_test.dart' as _vibrate_test;
import '_viewcampaignpage_test.dart' as _viewcampaignpage_test;
import '_widget_test.dart' as _widget_test;

void main() {
  _vibrate_test.main();
  _main_test.main();
  _homepage_test.main();
  _widget_test.main();
  _viewcampaignpage_test.main();
  _navigation_test.main();
}
